name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - README.md
      - "releases/**"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.platform}}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test
        run: go test -race -count 1 ./...

      - name: Coverage Test
        if: ${{ matrix.platform == 'ubuntu-latest' && github.ref_name == 'main' }}
        run: go test -count 1 -coverprofile=coverage.txt ./...

      - name: Upload Coverage
        if: ${{ matrix.platform == 'ubuntu-latest' && github.ref_name == 'main' }}
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d #v5.4.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: grafana/k6foundry

      - name: Generate Go Report Card
        if: ${{ matrix.platform == 'ubuntu-latest' && github.ref_name == 'main' }}
        uses: creekorful/goreportcard-action@1f35ced8cdac2cba28c9a2f2288a16aacfd507f9 # v1.0.0
